default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 1234
  host: localhost
  database: rent_a_bike

development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 1234
  host: localhost
  database: rent_a_bike

production:
  <<: *default
  database: rent-a-bike
  username: postgres
  password: 1234
